# Generated by Django 4.2.13 on 2024-06-08 19:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('unidad', models.CharField(blank=True, max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='image/materials')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('codigo', models.CharField(blank=True, max_length=255)),
                ('director_proyecto', models.CharField(blank=True, max_length=255)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='SST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='image/sst')),
            ],
            options={
                'verbose_name': 'SST',
                'verbose_name_plural': 'SST',
                'db_table': 'sst',
            },
        ),
        migrations.CreateModel(
            name='TypeSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='image/signs')),
            ],
            options={
                'verbose_name': 'Tipo Señal',
                'verbose_name_plural': 'Tipos Señales',
                'db_table': 'types_sings',
            },
        ),
        migrations.CreateModel(
            name='Signs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signs', to='detection.typesigns')),
            ],
            options={
                'verbose_name': 'Señal',
                'verbose_name_plural': 'Señales',
                'db_table': 'sings',
            },
        ),
        migrations.CreateModel(
            name='DetectionSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_original', models.ImageField(blank=True, null=True, upload_to='original/sst')),
                ('imagen_procesada', models.ImageField(blank=True, null=True, upload_to='procesada/sst')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('deteccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_sst', to='detection.sst')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_sst', to='detection.projects')),
            ],
            options={
                'verbose_name': 'Deteccion SST',
                'verbose_name_plural': 'Detecciones SST',
                'db_table': 'detections_sst',
            },
        ),
        migrations.CreateModel(
            name='DetectionSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_original', models.ImageField(blank=True, null=True, upload_to='original/signs')),
                ('imagen_procesada', models.ImageField(blank=True, null=True, upload_to='procesada/signs')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_signs', to='detection.projects')),
                ('senal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_signs', to='detection.signs')),
            ],
            options={
                'verbose_name': 'Detección Senal',
                'verbose_name_plural': 'Detección Senales',
                'db_table': 'detections_signs',
            },
        ),
        migrations.CreateModel(
            name='DetectionMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_original', models.ImageField(blank=True, null=True, upload_to='original/materials')),
                ('imagen_procesada', models.ImageField(blank=True, null=True, upload_to='procesada/materials')),
                ('cantidad', models.FloatField(default=0)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_materials', to='detection.materials')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_materials', to='detection.projects')),
            ],
            options={
                'verbose_name': 'Detección Material',
                'verbose_name_plural': 'Detección Materiales',
                'db_table': 'detections_materials',
            },
        ),
    ]
