# Generated by Django 4.2.13 on 2024-06-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_alter_detectionsigns_options_remove_projects_latitud_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typesigns',
            old_name='tipo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='typesigns',
            name='codigo',
        ),
        migrations.AddField(
            model_name='signs',
            name='codigo',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
